<?php

/**
 * My_Orm_Entity_Artiste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Identifiant
 * @property string $Nom
 * @property string $Description
 * @property integer $IdentifiantImage
 * @property integer $IdentifiantVideo
 * @property integer $IdentifiantMiniature
 * @property My_Orm_Miniature $Miniature
 * @property My_Orm_Image $Image
 * @property My_Orm_Video $Video
 * @property Doctrine_Collection $Genreartiste
 * @property Doctrine_Collection $Musique
 * @property Doctrine_Collection $Nationaliteartiste
 * @property Doctrine_Collection $Prestation
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class My_Entity_Artiste extends My_Base
{
    public function setTableDefinition()
    {
        $this->setTableName('artiste');
        $this->hasColumn('Identifiant', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Nom', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('Description', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('IdentifiantImage', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('IdentifiantVideo', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('IdentifiantMiniature', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('My_Orm_Miniature as Miniature', array(
             'local' => 'IdentifiantMiniature',
             'foreign' => 'Identifiant'));

        $this->hasOne('My_Orm_Image as Image', array(
             'local' => 'IdentifiantImage',
             'foreign' => 'Identifiant'));

        $this->hasOne('My_Orm_Video as Video', array(
             'local' => 'IdentifiantVideo',
             'foreign' => 'Identifiant'));

        $this->hasMany('My_Orm_GenreArtiste as GenreArtiste', array(
             'local' => 'Identifiant',
             'foreign' => 'IdentifiantArtiste'));

        $this->hasMany('My_Orm_Musique as Musique', array(
             'local' => 'Identifiant',
             'foreign' => 'IdentifiantArtiste',
             'onDelete' => 'CASCADE'));

        $this->hasMany('My_Orm_NationaliteArtiste as NationaliteArtiste', array(
             'local' => 'Identifiant',
             'foreign' => 'IdentifiantArtiste'));

        $this->hasMany('My_Orm_Prestation as Prestation', array(
             'local' => 'Identifiant',
             'foreign' => 'IdentifiantArtiste',
             'onDelete' => 'CASCADE'));
    }
}