<?php

/**
 * My_Orm_Entity_Genreartiste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $IdentifiantGenre
 * @property integer $IdentifiantArtiste
 * @property My_Orm_Genre $Genre
 * @property My_Orm_Artiste $Artiste
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class My_Entity_GenreArtiste extends My_Base
{
    public function setTableDefinition()
    {
        $this->setTableName('genreartiste');
        $this->hasColumn('IdentifiantGenre', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('IdentifiantArtiste', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('My_Orm_Genre as Genre', array(
             'local' => 'IdentifiantGenre',
             'foreign' => 'Identifiant'));

        $this->hasOne('My_Orm_Artiste as Artiste', array(
             'local' => 'IdentifiantArtiste',
             'foreign' => 'Identifiant'));
    }
}