<?php

/**
 * My_Orm_Entity_Live
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Identifiant
 * @property integer $IdentifiantPrestationMusique
 * @property My_Orm_Prestationmusique $Prestationmusique
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class My_Entity_Live extends My_Base
{
    public function setTableDefinition()
    {
        $this->setTableName('live');
        $this->hasColumn('Identifiant', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('IdentifiantPrestationMusique', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('My_Orm_PrestationMusique as PrestationMusique', array(
             'local' => 'IdentifiantPrestationMusique',
             'foreign' => 'Identifiant'));
    }
}