<?php

/**
 * My_Orm_Entity_Musique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Identifiant
 * @property string $Titre
 * @property string $Paroles
 * @property integer $IdentifiantVideo
 * @property integer $IdentifiantArtiste
 * @property My_Orm_Video $Video
 * @property My_Orm_Artiste $Artiste
 * @property Doctrine_Collection $Prestationmusique
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class My_Entity_Musique extends My_Base
{
    public function setTableDefinition()
    {
        $this->setTableName('musique');
        $this->hasColumn('Identifiant', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Titre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('Paroles', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('IdentifiantVideo', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IdentifiantArtiste', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('My_Orm_Video as Video', array(
             'local' => 'IdentifiantVideo',
             'foreign' => 'Identifiant'));

        $this->hasOne('My_Orm_Artiste as Artiste', array(
             'local' => 'IdentifiantArtiste',
             'foreign' => 'Identifiant'));

        $this->hasMany('My_Orm_PrestationMusique as PrestationMusique', array(
             'local' => 'Identifiant',
             'foreign' => 'IdentifiantMusique'));
    }
}