<?php

/**
 * My_Orm_Entity_Prestationmusique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Identifiant
 * @property integer $IdentifiantMusique
 * @property integer $IdentifiantPrestation
 * @property My_Orm_Musique $Musique
 * @property My_Orm_Prestation $Prestation
 * @property Doctrine_Collection $Live
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class My_Entity_PrestationMusique extends My_Base
{
    public function setTableDefinition()
    {
        $this->setTableName('prestationmusique');
        $this->hasColumn('Identifiant', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('IdentifiantMusique', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('IdentifiantPrestation', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('My_Orm_Musique as Musique', array(
             'local' => 'IdentifiantMusique',
             'foreign' => 'Identifiant'));

        $this->hasOne('My_Orm_Prestation as Prestation', array(
             'local' => 'IdentifiantPrestation',
             'foreign' => 'Identifiant'));

        $this->hasMany('My_Orm_Live as Live', array(
             'local' => 'Identifiant',
             'foreign' => 'IdentifiantPrestationMusique'));
    }
}