<?php

/**
 * My_Orm_Action
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Action extends My_Entity_Action {

    public static function find($pIdentifiant) {

        $oAction = Doctrine::getTable('My_Orm_Action')
                ->createQuery('a')
                ->leftJoin('a.Image as im')
                ->leftJoin('a.Association as asso')
                ->leftJoin('a.Adresse as ad')
                ->where('a.Identifiant = ?', $pIdentifiant)
                ->fetchOne();

        if ($oAction == false) {
            return null;
        }
        return $oAction;
    }

    public static function findAll() {

        $aActions = Doctrine::getTable('My_Orm_Action')
                ->createQuery('a')
                ->leftJoin('a.Image as im')
                ->leftJoin('a.Association as asso')
                ->leftJoin('a.Adresse as ad')
                ->execute();

        if ($aActions == false) {
            return null;
        }

        return $aActions;
    }
    
    public static function findSome($pIdentifiantAssociation, $ptoday) {

        $aInformations = Doctrine::getTable('My_Orm_Action')
                ->createQuery('a')
                ->innerJoin('a.Association as asso')
                ->innerJoin('a.Adresse as adr')
                ->innerJoin('a.Image as i')
                ->where('a.IdentifiantAssociation = ?', $pIdentifiantAssociation)
                ->andWhere('a.DateAction < ?',$ptoday)
                ->orderBy('a.DateAction')
                ->execute();

        if ($aInformations == false) {
            return null;
        }

        return $aInformations;
    }
    
    public static function findAgenda($pIdentifiantAssociation, $ptoday) {

        $aInformations = Doctrine::getTable('My_Orm_Action')
                ->createQuery('a')
                ->innerJoin('a.Association as asso')
                ->innerJoin('a.Adresse as adr')
                ->innerJoin('a.Image as i')
                ->where('a.IdentifiantAssociation = ?', $pIdentifiantAssociation)
                ->andWhere('a.DateAction >= ?',$ptoday)
                ->orderBy('a.DateAction')
                ->execute();

        if ($aInformations == false) {
            return null;
        }

        return $aInformations;
    }
}
