<?php

/**
 * My_Orm_Artiste
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Artiste extends My_Entity_Artiste {

    public static function find($pIdentifiant) {

        $oArtiste = Doctrine::getTable('My_Orm_Artiste')
                ->createQuery('a')
                ->innerJoin('a.Image as i')
                ->innerJoin('a.Video as v')
                ->innerJoin('a.NationaliteArtiste na')
                ->innerJoin('na.Nationalite n')
                ->innerJoin('a.GenreArtiste ga')
                ->innerJoin('ga.Genre g')
                ->where('a.Identifiant = ?', $pIdentifiant)
                ->fetchOne();

        if ($oArtiste == false) {
            return null;
        }

        return $oArtiste;
    }

    public static function findAll() {

        $aArtistes = Doctrine::getTable('My_Orm_Artiste')
                ->createQuery('a')
                ->execute();

        if ($aArtistes == false) {
            return null;
        }

        return $aArtistes;
    }

    public static function findForDelete($pIdentifiant) {

        $oArtiste = Doctrine::getTable('My_Orm_Artiste')
                ->createQuery('a')
                ->innerJoin('a.Image as i')
                ->innerJoin('a.Video as v')
                ->where('a.Identifiant = ?', $pIdentifiant)
                ->fetchOne();

        if ($oArtiste == false) {
            return null;
        }

        return $oArtiste;
    }

}
