<?php

/**
 * My_Orm_Association
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Association extends My_Entity_Association {

    public static function find($pIdentifiant) {

        $oAssociation = Doctrine::getTable('My_Orm_Association')
                ->createQuery('a')
                ->leftJoin('a.Information as i')
                ->leftJoin('a.Action as ac')
                ->where('a.Identifiant = ?', $pIdentifiant)
                ->fetchOne();

        if ($oAssociation == false) {
            return null;
        }
        return $oAssociation;
    }

    public static function findAll() {

        $aAssociations = Doctrine::getTable('My_Orm_Association')
                ->createQuery('a')
                ->leftJoin('a.Information as i')
                ->leftJoin('a.Action as ac')
                ->execute();

        if ($aAssociations == false) {
            return null;
        }

        return $aAssociations;
    }

}
