<?php

/**
 * My_Orm_Edition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Edition extends My_Entity_Edition
{
    public static function find($pIdentifiant){
        
        $oEdition = Doctrine::getTable('My_Orm_Edition')
                        ->createQuery('e')
                        ->where('e.Identifiant = ?', $pIdentifiant)
                        ->fetchOne();
        
        if($oEdition == false){
            return null;
        }
        
        return $oEdition;
    }
    
    public static function findByYear($pYear){
        
        $oEdition = Doctrine::getTable('My_Orm_Edition')
                        ->createQuery('e')
                        ->where('e.Annee = ?', $pYear)
                        ->fetchOne();
        
        if($oEdition == false){
            return null;
        }
        
        return $oEdition;
    }    

    
    public static function findAll(){
        
        $aEditions = Doctrine::getTable('My_Orm_Edition')
                        ->createQuery('e')
                        ->execute();
        
        if($aEditions == false){
            return null;
        }
        
        return $aEditions;
    }
}