<?php

/**
 * My_Orm_Genre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Genre extends My_Entity_Genre
{
    public static function find($pIdentifiant){
        
        $oGenre = Doctrine::getTable('My_Orm_Genre')
                    ->createQuery('g')
                    ->where('g.Identifiant = ?', $pIdentifiant)
                    ->fetchOne();
        
        if($oGenre == false){
            return null;
        }
        
        return $oGenre;
    }
    
    public static function findAll(){
        
        $aGenres = Doctrine::getTable('My_Orm_Genre')
                        ->createQuery('g')
                        ->execute();
        
        if($aGenres == false){
            return null;
        }
        
        return $aGenres;
    }
}