<?php

/**
 * My_Orm_Image
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Image extends My_Entity_Image
{
    public static function find($pIdentifiant){

        $oImage = Doctrine::getTable('My_Orm_Image')
                        ->createQuery('i')
                        ->where('i.Identifiant = ?', $pIdentifiant)
                        ->fetchOne();

        if($oImage == false){
            return null;
        }

        return $oImage;
    }

    public static function findAll(){

        $aImages = Doctrine::getTable('My_Orm_Image')
                        ->createQuery('i')
                        ->fetchArray();

        if($aImages == false){
            return null;
        }

        return $aImages;
    }

}