<?php

/**
 * My_Orm_Information
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Information extends My_Entity_Information {

    public static function find($pIdentifiant) {
        $oInformation = Doctrine::getTable('My_Orm_Information')
                ->createQuery('i')
                ->innerJoin('i.Association as a')
                ->where('i.Identifiant = ?', $pIdentifiant)
                ->fetchOne();

        if ($oInformation == false) {
            return null;
        }

        return $oInformation;
    }

    public static function findByTitre($pTitre, $pIdentifiantAssociation) {
        $oInformation = Doctrine::getTable('My_Orm_Information')
                ->createQuery('i')
                ->innerJoin('i.Association as a')
                ->where('a.Identifiant = ?', $pIdentifiantAssociation)
                ->andWhere('i.Titre = ?', $pTitre)
                ->fetchOne();

        if ($oInformation == false) {
            return null;
        }

        return $oInformation;
    }

    public static function findAll() {
        $aInformations = Doctrine::getTable('My_Orm_Information')
                ->createQuery('i')
                ->execute();

        if ($aInformations == false) {
            return null;
        }

        return $aInformations;
    }

    public static function findSome($pIdentifiantAssociation, $pNbInfo) {

        $aInformations = Doctrine::getTable('My_Orm_Information')
                ->createQuery('i')
                ->where('i.IdentifiantAssociation = ?', $pIdentifiantAssociation)
                ->orderBy('i.Identifiant DESC')
                ->limit($pNbInfo)
                ->execute();

        if ($aInformations == false) {
            return null;
        }

        return $aInformations;
    }

}
