<?php

/**
 * My_Orm_Live
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Live extends My_Entity_Live {

    public static function find() {
        $oLive = Doctrine::getTable('My_Orm_Live')
                ->createQuery('l')
                ->innerJoin('l.PrestationMusique as pm')
                ->fetchOne();

        if ($oLive == false) {
            return null;
        }

        return $oLive;
    }

}
