<?php

/**
 * My_Orm_Musique
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Musique extends My_Entity_Musique
{
    public static function find($pIdentifiant)
    {
        $oMusique = Doctrine::getTable('My_Orm_Musique')
                            ->createQuery('m')
                            ->where('m.Identifiant = ?',$pIdentifiant)
                            ->fetchOne();
                            
        if ($oMusique == false){
            return null;
        }
        
        return $oMusique;
    }
    
    public static function findAll()
    {
        $aMusiques = Doctrine::getTable('My_Orm_Musique')
                            ->createQuery('m')
                            ->fetchArray();
                            
        if ($aMusiques == false){
            return null;
        }
        
        return $aMusique;
    }
    

}