<?php

/**
 * My_Orm_Nationalite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Nationalite extends My_Entity_Nationalite
{
    public static function find($pIdentifiant)
    {
        $oNationalite = Doctrine::getTable('My_Orm_Nationalite')
                            ->createQuery('n')
                            ->where('n.Identifiant = ?',$pIdentifiant)
                            ->fetchOne();
                            
        if ($oNationalite == false){
            return null;
        }
        
        return $oNationalite;
    }
    
    public static function findAll()
    {
        $aNationalite = Doctrine::getTable('My_Orm_Nationalite')
                            ->createQuery('n')
                            ->execute();
                            
        if ($aNationalite == false){
            return null;
        }
        
        return $aNationalite;
    }
    
}