<?php

/**
 * My_Orm_Scene
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class My_Orm_Scene extends My_Entity_Scene
{
    public static function find($pIdentifiant)
    {
        $oScene = Doctrine::getTable('My_Orm_Scene')
                            ->createQuery('s')
                            ->where('s.Identifiant = ?',$pIdentifiant)
                            ->fetchOne();
                            
        if ($oScene == false){
            return null;
        }
        
        return $oScene;
    }
    
    public static function findAll()
    {
        $aScene = Doctrine::getTable('My_Orm_Scene')
                            ->createQuery('s')
                            ->execute();
                            
        if ($aScene == false){
            return null;
        }
        
        return $aScene;
    }
}